config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :jobs do
    resources :resumes
  end
  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title,presence: true
  validates :wage_lower_bound,presence:true
  validates :wage_upper_bound,presence:true
  validates :wage_lower_bound,numericality:{greater_than: 0}
  def publish!
    self.is_hidden=false
    self.save
  end
  def hide!
    self.is_hidden=true
    self.save
  end
  scope :published,->{where(is_hidden:false)}
  scope :recent,->{order('created_at DESC')}
  has_many :resumes
end

app/models/resume.rb
class Resume < ApplicationRecord
  validates :content,presence:true
  belongs_to :user
  belongs_to :job
  mount_uploader :attachment,AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end
  has_many :resumes
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user! ,only: [:new,:create,:edit,:update,:destroy]
  before_action :require_is_admin
  layout "admin"
  def index
    @jobs=Job.recent.paginate(:page=>params[:page],:per_page=>15)
  end

  def new
    @job=Job.new
  end

  def show
    @job=Job.find(params[:id])
  end

  def edit
    @job=Job.find(params[:id])
  end

  def create
    @job=Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def update
    @job=Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job=Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path
  end

  def publish
    @job=Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job=Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  private
  def job_params
    params.require(:job).permit(:title,:description,:wage_lower_bound,:wage_upper_bound,
      :contact_email,:is_hidden)
  end



end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  def index
    @job=Job.find(params[:job_id])
    @resumes=@job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_is_admin
    if !current_user.admin?
      flash[:alert]='you are not admin'
      redirect_to jobs_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!,only:[:new,:create,:edit,:update,:destroy]
  def index
    # @jobs=Job.where(:is_hidden=>false)
    @jobs=Job.published.paginate(:page=>params[:page],:per_page=>15)
    if params[:c].present?
      @category=params[:c]
      @jobs=@jobs.where(job_type:@category)
    end
    @jobs=case params[:order]
  when 'by_lower_bound'
    @jobs.order('wage_lower_bound DESC')
  when 'by_upper_bound'
    @jobs.order('wage_upper_bound DESC')
  else
    @jobs.recent
  end
  end
  def new
    @job=Job.new
  end
  def show
    @job=Job.find(params[:id])
    if @job.is_hidden
      flash[:warning]="This job is already been archieved"
      redirect_to root_path
    end
  end
  def edit
    @job=Job.find(params[:id])
  end
  def create
    @job=Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end
  def update
    @job=Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end
  def destroy
    @job=Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:title,:description,:wage_lower_bound,:wage_upper_bound,:contact_email,
      :is_hidden,:job_type)
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  def new
    @job=Job.find(params[:job_id])
    @resume=Resume.new
  end
  def create
    @job=Job.find(params[:job_id])
    @resume=Resume.new(resume_params)
    @resume.job=@job
    @resume.user=current_user
    if @resume.save
      flash[:notice]="成功提交简历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end
  private
  def resume_params
    params.require(:resume).permit(:content,:attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @jobs=Job.where(:is_hidden=>false)
    @jobs=Job.published
    if params[:c].present?
      @category=params[:c]
      @jobs=@jobs.where(job_type:@category)
    end
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span,"",:class=>"fa fa-lock")
    else
      content_tag(:span,"",:class=>"fa fa-globe")
    end
  end
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  def resource
    @resource ||= User.new
  end
  def resource_class
    User
  end
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES={alert:"danger",notice:"success",warning:"warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym,key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert","notice","warining"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1>Edit a job </h1>
<%=simple_form_for [:admin,@job] do |f| %>
<%=f.input :title%>
<%=f.input :description%>
<%=f.input :wage_lower_bound %>
<%=f.input :wage_upper_bound %>
<%=f.input :contact_email %>
<%=f.submit "submit" %>
<%=f.input :is_hidden %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%=link_to('Add a job',new_admin_job_path,:class=>"btn btn-success")%>
</div>
<br />
<br />
<table class="table table-boldered">
  <thead>
    <tr>
      <th>招聘岗位</th>
      <th>简历数量</th>
      <th>最低工资</th>
      <th>最高工资</th>
      <th>管理</th>
      <th>发布时间</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>
          <%=link_to(job.title,admin_job_path(job))%>
          <%=render_job_status(job)%>
          <!-- <% if job.is_hidden %>
            <span class="glyphicon glyphicon-globe"></span>
          <% else %>
            <span class="glyphicon glyphicon-lock"></span>
          <% end %> -->
        </td>

        <td>
          <%=link_to(job.resumes.count,admin_job_resumes_path(job))%>
        </td>
        <td><%=job.wage_lower_bound%></td>
        <td><%=job.wage_upper_bound%></td>
        <td>
          <%=link_to('Edit',edit_admin_job_path(job),:class=>"btn btn-xs btn-primary")%> |
          <%=link_to('Delete',admin_job_path(job),:method=>:delete,:class=>"btn btn-xs btn-warning",:data=>{:confirm=>"Are you sure?"})%> |
          <% if job.is_hidden %>
            <%=link_to('publish',publish_admin_job_path(job),:method=>:post,:class=>"btn btn-xs btn-success")%>
          <% else %>
            <%=link_to('hide',hide_admin_job_path(job),:method=>:post, :class=>"btn btn-xs btn-info")%>
          <% end %>
        </td>
        <td><%=job.created_at%></td>
      </tr>
    <% end %>
  </body>
</table>
<div class="text-center">
  <%=will_paginate @jobs %>
</div>

app/views/admin/jobs/new.html.erb
<h1>Add a job</h1>
<%=simple_form_for [:admin,@job] do |f| %>
<%=f.input :title%>
<%=f.input :description%>
<%=f.input :wage_lower_bound%>
<%=f.input :wage_upper_bound%>
<%=f.input :contact_email%>
<%=f.input :job_type%>
<%=f.submit "确定"%>
<%=f.input :is_hidden%>
<% end %>

app/views/admin/jobs/show.html.erb
<h1><%=@job.title%></h1>

  <%=simple_format(@job.description)%>
  <%=@job.wage_lower_bound%>
  <%=@job.wage_upper_bound%>
  <%=@job.contact_email%>
  <%=@job.created_at%>
  <%=link_to('Back',:back,:class=>"btn btn-warning")%>

app/views/admin/resumes/_resumes.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-2">
        <h3 class="panel-title">
          <%=resume.user.email%>
        </h3>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="trix-content">
      <p><%=simple_format(resume.content)%></p>
    </div>
    <hr />
    <% if resume.attachment.present? %>
      <i class="fa fa-paperclip"></i>
      <%=link_to('下载附件',resume.attachment_url)%>
    <%else%>
      No Attachment
    <%end%>
  </div>
</div>

app/views/admin/resumes/index.html.erb
<h2><%=@job.title%>-简历列表</h2>
<hr  />
<%=render :partial=>"resumes",:collection=>@resumes,:as=>:resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,value| %>
  <div class="alert alert-dismissable alert-<%=flash_class(key)%>">
    <button class="close" data-dismiss="alert">&times</button>
    <%= value %>
  </div>
  <% end%>
<% end%>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright @Rails101
    <br>Design by Yuansus
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class=" navbar navbar-default " role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">Job Listing</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user %>
            <!-- <li><%=link_to('Sign up',new_user_registration_path)%></li>
            <li><%=link_to('Log in',new_user_session_path)%></li> -->
            <li><a href="#" data-toggle="modal" data-target="#signup-modal">Sign up</a></li>
            <li><a href="#" data-toggle="modal" data-target="#login-modal">Log in</a></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi,<%=current_user.email%>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin?  %>
                <li><%=link_to('Admin panel',admin_jobs_path)%></li>
                <% end %>
                <li><%=link_to('Log out',destroy_user_session_path,method: :delete)%></li>
              </ul>
            </li>
          <% end %>
        </ul>
    </div>
    </div>
</nav>
<!-- pop login windown -->
<!-- <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, required: true, autofocus: true %>
           <%= f.input :password, required: true %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div></div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>Sign up</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div> -->


<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <div class="modal-header">
          <h2 class="text-center">Sign up</h2>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name),
                               :html => {:id => "sign_up_user"},
                               :format => :json,
                               :remote => true ) do |f| %>
          <%= devise_error_messages! %>

          <div class="input-group">
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-envelope"></span>
            </span>
            <%= f.email_field :email, autofocus: true, required: true, class: "form-control", placeholder: "Email" %>
          </div>

          <br>

          <div class="input-group">
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-lock"></span>
            </span>
            <%= f.password_field :password, autocomplete: "off", required: true,minlength: 8, class: "form-control", placeholder: "Password(8 character minimum)" %>
          </div>

          <br>

          <div class="input-group">
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-lock"></span>
            </span>
            <%= f.password_field :password_confirmation, autocomplete: "off", required: true, minlength: 8, class: "form-control", placeholder: "Repeat password" %>
          </div>

          <div class="form-actions">
            <br>
            <%= f.submit "Sign up", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        <div class="links pull-right">
          <button class="btn btn-info btn-small" data-toggle="modal" data-target="#login-modal" data-dismiss='modal'>Log in</button><br />
          <br>
          <div class="center-block">
            <button class="btn btn-info btn-small text-center" data-toggle="modal" data-target="#forgot-modal" data-dismiss='modal'>Forgot password?</button><br />
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="login-modal" role="dialog">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2 class="text-center">Log in</h2>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name),
                               :html => {:id => "log_in_user"},
                               :format => :json,
                               :remote => true ) do |f| %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-envelope"></span>
            </span>
            <%= f.email_field :email, autofocus: true, required: true, class: "form-control", placeholder:"Email" %>
          </div>

          <br>

          <div class="input-group">
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-lock"></span>
            </span>
            <%= f.password_field :password, autocomplete: "off", required: true, class: "form-control", placeholder: "Password" %>
          </div>

          <% if devise_mapping.rememberable? -%>
          <div class="checkbox col-md-12" style="padding-left:1.5em;">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
          <% end -%>

          <div class="form-actions">
            <br>
            <%= f.submit "Log in", class: 'btn btn-success', id: 'login_btn' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        <div class="links pull-right">
          <button class="btn btn-info btn-small" data-toggle="modal" data-target="#signup-modal" data-dismiss='modal'>Sign up</button><br />
          <br>
          <div class="center-block">
            <button class="btn btn-info btn-small text-center" data-toggle="modal" data-target="#forgot-modal" data-dismiss='modal'>Forgot password?</button><br />
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="forgot-modal" role="dialog">
    <div class="modal-dialog">
        <div class="loginmodal-container">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2>Forgot your password?</h2>
            </div>
            <div class="modal-body">
                <%= form_for(resource, as: resource_name, url: password_path(resource_name),
                                                :html => {:id => "forgot_password_user"},
                                                :format => :json,
                                                :remote => true ) do |f| %>
                    <%= devise_error_messages! %>

                    <div class="input-group">
                      <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                      </span>
                      <%= f.email_field :email, autofocus: true, required:true, class: "form-control", placeholder:"Email" %>
                    </div>

                  <div class="form-actions">
                    <br>
                    <%= f.submit "Send me reset password instructions", class: 'btn btn-success' %>
                  </div>
                <% end %>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                <div class="links pull-right">
                    <button class="btn btn-info btn-small" data-toggle="modal" data-target="#login-modal" data-dismiss='modal'>Log in</button><br />
                    <br>
                    <div class="center-block">
                    <button class="btn btn-info btn-small" data-toggle="modal" data-target="#signup-modal" data-dismiss='modal'>Sign up</button><br />
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/jobs/index.html.erb
<div class="dropdown clearfix pull-right">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-order"
    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">排序<span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-order">
    <li><%=link_to("按照最低工资排序",jobs_path(:c=>@category,:order=>"by_lower_bound"))%></li>
    <li><%=link_to("按照最高工资排序",jobs_path(:c=>@category,:order=>"by_upper_bound"))%></li>
    <li><%=link_to("按照发布时间排序",jobs_path(:c=>@category) )%></li>
  </ul>
</div>
<table class="table table-boldered">
  <thead>
    <tr>
      <th>招聘岗位</th>
      <th>最低工资</th>
      <th>最高工资</th>
      <th>发布时间</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%=link_to(job.title,job_path(job))%></td>
        <td><%=job.wage_lower_bound%></td>
        <td><%=job.wage_upper_bound%></td>
        <td><%=job.created_at%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%=will_paginate @jobs %>
</div>

app/views/jobs/show.html.erb
<h1><%=@job.title%></h1>
<label>description:</label>
<%=simple_format(@job.description)%>
<%=@job.wage_lower_bound%> <br />
<%=@job.wage_upper_bound%><br />
<%=@job.contact_email%><br />
<%=@job.created_at%><br />
<%=@job.wage_lower_bound%><br />
<%=link_to('Back',:back,:class=>"btn btn-warning")%>
<div class="text-center">
  <%=link_to('投递简历',new_job_resume_path(@job),:style=>"font-size:30px;
    text-decoration:underline;")%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Listing</title>
  <%=csrf_meta_tags %>
  <%=stylesheet_link_tag 'application',media:'all','data-turbolinks-track':'reload'%>
  <%=javascript_include_tag 'application','data-turbolinks-track':'reload'%>

</head>
<body>
  <div class="container-fluid">
    <%=render "common/navbar"%>
    <%=render "common/flashes"%>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width:300px;padding-top:20px;">
          <li class="active"><%=link_to("jobs",admin_jobs_path)%></li>
        </ul>
      </div>
      <div class="col-md-10">
        <%=yield%>
      </div>
    </div>
    <%=render "common/footer"%>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joblisting4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <%=render "common/navbar"%>
        <%=render "common/flashes"%>
        <%= yield %>

      </div>
    </div>

    <%=render "common/footer"%>
  </body>
</html>

app/views/resumes/new.html.erb
<h3>投递简历到-<%=@job.title%></h3>
<hr>
<%=simple_form_for [@job,@resume] do |f| %>
  <%=f.input :content%>
  <%=f.input :attachment%>
  <%=f.submit "发送"%>
<% end %>